// Mocks generated by Mockito 5.4.4 from annotations
// in zap_scanner/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;
import 'package:zap_scanner/models/report.dart' as _i6;
import 'package:zap_scanner/services/db_service.dart' as _i5;
import 'package:zap_scanner/services/zap_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ZapService].
///
/// See the documentation for Mockito's code generation for more information.
class MockZapService extends _i1.Mock implements _i2.ZapService {
  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get apiKey => (super.noSuchMethod(
        Invocation.getter(#apiKey),
        returnValue: _i3.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
        returnValueForMissingStub: _i3.dummyValue<String>(
          this,
          Invocation.getter(#apiKey),
        ),
      ) as String);

  @override
  _i4.Future<String?> getVersion() => (super.noSuchMethod(
        Invocation.method(
          #getVersion,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> newSession() => (super.noSuchMethod(
        Invocation.method(
          #newSession,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> startSpider(String? targetUrl) => (super.noSuchMethod(
        Invocation.method(
          #startSpider,
          [targetUrl],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> spiderStatus(String? scanId) => (super.noSuchMethod(
        Invocation.method(
          #spiderStatus,
          [scanId],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> startActiveScan(String? targetUrl) => (super.noSuchMethod(
        Invocation.method(
          #startActiveScan,
          [targetUrl],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> activeScanStatus(String? scanId) => (super.noSuchMethod(
        Invocation.method(
          #activeScanStatus,
          [scanId],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String> getReportHtml() => (super.noSuchMethod(
        Invocation.method(
          #getReportHtml,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getReportHtml,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i3.dummyValue<String>(
          this,
          Invocation.method(
            #getReportHtml,
            [],
          ),
        )),
      ) as _i4.Future<String>);
}

/// A class which mocks [DbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDbService extends _i1.Mock implements _i5.DbService {
  @override
  _i4.Future<void> openBox() => (super.noSuchMethod(
        Invocation.method(
          #openBox,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> saveReport(_i6.Report? report) => (super.noSuchMethod(
        Invocation.method(
          #saveReport,
          [report],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<_i6.Report> getAllReports() => (super.noSuchMethod(
        Invocation.method(
          #getAllReports,
          [],
        ),
        returnValue: <_i6.Report>[],
        returnValueForMissingStub: <_i6.Report>[],
      ) as List<_i6.Report>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
